### ISSUE TITLE
Type of Callback

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#10]
The `rdev::Callback` type is a function pointer (`fn`) and not a `std::ops::Fn` (`Fn`), so it is not possible to use closures. Changing to `Fn` would probably break backwards compatibility, but it would be relatively easy for users to fix. In the following example I want to send the mouse positions over a chanel (which is not `Sync`, so I can't share the whole thing between threads, just give out the ends individually).

```rust
use rdev::{listen, Event, EventType};
use std::sync::mpsc::{channel, Sender, Receiver};

fn callback(event: Event, sender: Sender<(f64, f64)>) {
    match event.event_type {
        EventType::MouseMove{x, y} => {
            sender.send((x,y));
        }
        _ => {}
    }
}

fn main() {
    let (send, recv) = channel();
    // bind callback's send to local variable send
    let bound_callback = |x| callback(x, send);
    listen(bound_callback); // <- error here, bound_callback is `Fn`, not `fn`
    // spawn a new thread to receive
}

```
Changing the type of Callback would be awesome, but it might make more sense for you to use `futures::stream::Stream` (basically a series of `Futures`) instead of callbacks for the next major release. This would majorly break backwards compatibility in a way that is hard for users to fix. The rust ecosystem is heavily investing in futures, so it seems like a good choice.

**Comment by Narsil** [comment]
Hi @maxbla,

This current project is for me to learn rust, so I would be glad to improve it's rustiness. For now I stayed as close as OS as possible, because it was just the simplest route for me.

I'll try moving to std::ops::Fn if it doesn't break backward compatibilty. As for streams I need to look into it, are you aware of any projects that convert classical C callbacks into Stream from rust API ?

**Comment by maxbla** [comment]
> This current project is for me to learn rust, so I would be glad to improve it's rustiness.

Awesome!

> I'll try moving to std::ops::Fn if it doesn't break backward compatibilty.

I started trying to do this myself, but gave up after an hour. I tried removing the Callback type and replacing it with a generic over `Fn(Event)`. I ran into trouble with lifetimes when trying to assign my callback to GLOBAL_CALLBACK (which must be `'static`). I suspect some asynchronous primitives could help here. I'll mess with it tomorrow.

> are you aware of any projects that convert classical C callbacks into Stream from rust API ?

No, but I do not know the internal workings of any Rust Projects that use C callbacks. I suspect something like the following would work. Create a callback which writes `rdev::Event`s to a `futures::channel::mpsc::UnboundedSender` the unbounded reciever corresponding to that sender implements Stream.

**Comment by Narsil** [comment]
I tentatively tried here #11 . I moved from `fn(Event)` to `&'static dyn Fn(Event)`. Seems to be working with closures now (with the reference cost). Reference seems to be necessary because we can't inline the closure anyway, so we Need a static lifetime for its reference.

It seems a bit arcanic, I would be more than happy to see if there was a non breaking way to implement the change.

**Comment by Narsil** [comment]
Oh I misread your example. You are trying to pass FnMut, and not Fn, (closure actually work today ! thanks to this https://github.com/rust-lang/rfcs/blob/master/text/1558-closure-to-fn-coercion.md).
For FnMut, I believe we would need quite a bit of change, no ? From various StackOverflow posts, it seems it's not really viable to encapsulate C callbacks into async. But I might be mistaken.

**Comment by Narsil** [comment]
Seems like I would need a runtime to do that properly, which is what I wanted to avoid.

Maybe another API entry points (via a feature) that implements a runtime and allows async to exist:
https://doc.rust-lang.org/nomicon/ffi.html#asynchronous-callbacks

This seems a bit too advanced for my current Rust understanding to do cleanly.

**Comment by maxbla** [comment]
> You are trying to pass FnMut, and not Fn, (closure actually work today ! thanks to this

That doesn't apply to what I'm trying to do, because as your link says

> A closure that does not move, borrow, or otherwise access (capture) local variables should be coercable to a function pointer (fn).

My closure does capture a local variable, so it doesn't coerce to `fn`. Also my function is not a `FnMut` - it does not mutate anything, only send messages through a channel. I've provided another example that runs on my computer with type annotations to prove it is not an `FnMut`, but an `Fn`
<details>
I made some modifications so this is valid rust, and not just an outline of what code would do

``` rust
use rdev::{listen, Event, EventType};
use std::sync::mpsc::{channel, Sender, Receiver};
use std::time::SystemTime;

fn callback(event: Event, sender: Sender<(f64, f64)>) {
    match event.event_type {
        EventType::MouseMove{x, y} => {
            sender.send((x,y)).expect("Couldn't send!");
        }
        _ => {}
    }
}

fn main() {
    let (send, recv) = channel();
    let bound_callback:Box<dyn Fn(Event)>= Box::new(|x| callback(x, send.clone()));
    bound_callback(rdev::Event{event_type: EventType::MouseMove{x:42., y:3.14}, name:None, time: SystemTime::now()});
    bound_callback(rdev::Event{event_type: EventType::MouseMove{x:2.71, y:0.577}, name:None, time: SystemTime::now()});
    println!("{:?}", recv.recv().expect("Couldn't recieve!"));
    println!("{:?}", recv.recv().expect("Couldn't recieve!"));
}
```
</details>

> &'static dyn Fn(Event)

The problem with a static lifetime is that I want to capture local variables, not `'static` ones. Ideally you would specify that a user provided callback has a lifetime of at least the lifetime of listen(), but I'm not sure how to do that.

> Seems like I would need a runtime to do that properly, which is what I wanted to avoid.

You would need an async executor to do the Stream thing. But async executors can be very simple. LocalPool is probably what you would look at using. Yeah, it makes sense to gate it behind a feature, especially for now, as there is still some uncertainty in the futures ecosystem.

**Comment by maxbla** [comment]
> Maybe another API entry points (via a feature) that implements a runtime and allows async to exist:
https://doc.rust-lang.org/nomicon/ffi.html#asynchronous-callbacks

Yeah, that seems like a great idea. As an intermediate step, you could implement it with a channel (synchronous `Stream` analogue), as that nomicon link suggests.

> Besides classical synchronization mechanisms like mutexes, one possibility in Rust is to use channels (in std::sync::mpsc) to forward data from the C thread that invoked the callback into a Rust thread.

 Here's one way to do that. Add a new function to `rdev` that is equivalent to `listen()`, but that takes no arguments and where the callback `send`s `Event`s into a channel. In this scenario, you also provide a `get_recv()` function that returns (a `Mutex` containing) the `Receiver` for the channel. A user can then write code like this:
```rust
fn main() {
    let _child = thread::spawn(move || {
        rdev::send_events_to_channel();
    });
    let recv  = rdev::get_recv().lock().unwrap();
    loop {
        //I can use local variables in this loop
        println!("{:?}", (*recv).recv().unwrap());
    }
}
```
By the way, there's nothing about this setup that requires it be in rdev. A user could accomplish the same thing by providing the described callback to `listen`. I think this should be in rdev because it is idiomatic Rust, and I suspect most users would want to use it this way.

If you do decide you like this idea, I have written it already and could easily submit a PR.

**Comment by Narsil** [comment]
Read that a bit late, I reworked my version in my current PR.

https://github.com/Narsil/rdev/pull/11

Feel free to push/show me yours, I'm eager to learn.

**Comment by maxbla** [comment]
> Feel free to push/show me yours, I'm eager to learn.

I don't know that what I wrote is worth learning from, but #17 contains the very minimal code I did write.

**Comment by maxbla** [comment]
New thoughts on this issue:
- The title is now misleading - I actually want to be able to use local variables in my callback, but doing so is forbidden by the borrow checker for good reason - `callback` is `static`
- Changing `callback` to `&'static dyn Fn` doesn't really help with that goal, and because closures coerce to `fn` pointers I don't see how the change is any different, besides requiring dynamic dispatch
- An easy way to allow users to use local variables involves returning a (synchronous, standard library) channel of `Event`s. It requires users to call `listen()` or some counterpart in a separate thread (basically the example code I wrote 2 comments up). I can polish my PR which does this in the next few days if you think it has a substantial chance of being merged.
- At some point in the future (pun intended), if the the synchronous channel PR is merged and you are satisfied with both it and the maturity of async, I can write a PR for an `async` channel (gated by a feature).

**Comment by Narsil** [comment]
I think have that capability should be in users hand, not really in that library (which main goal is to abstract away OSes idiosyncrasies in input monitoring).

If you find some clean way to do it, I think putting it as an example might be the best option for now.
