### ISSUE TITLE
consult sincerely some question

### ISSUE THREAD

**Issue by Java-S12138** [Narsil/rdev#109]
I'm new to the rust language, which consult sincerely some question for you.

In some cases, pressing the capslock then to press other key, I don't hope seconde key to implement default behavior.

So, Is there a method or library to block the default behavior from happening?

Thx!

**Comment by Narsil** [comment]
This crate has `unstable_grab` feature that shuold allow you to do what you want. It's unstable for a reason though, so your mileage may vary.

Check out the examples to see how it works.
