### ISSUE TITLE
No KeyUp/KeyDown event on OSX

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Narsil/rdev#12]
Hello !

Thank for this library, it's awesome ;-)
On OSX, I don't receive any Key Event - only flag events are received.

Do you have any idea why ?
I'm on OSX Catalina 10.15.2.

Thank you

**Comment by MarcAntoine-Arnaud** [comment]
I found the issue !

On OSX, application requires access to terminal.
To do that:
- Go to System & preferences
- in Security & Privacy section
- Privacy tab
- Input Monitoring label
- Enable `Terminal` application

So I close the issue.

**Comment by Narsil** [comment]
Yes, Should it be more proeminent on the README ?

**Comment by MarcAntoine-Arnaud** [comment]
I can be helpfull to add that at the bottom i think yes ;-)
