### ISSUE TITLE
callback return an event

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Narsil/rdev#16]
If I have right, the listen is configured as an enabled filter (https://developer.apple.com/documentation/coregraphics/cgeventtapoptions?language=objc)

Is it possible to update the current event ?

**Comment by Narsil** [comment]
Not with the current implementation.

Adding `grab` is somehow something I would like to add but X11, Windows and Mac have quite different approaches for that so it's going to be trickier to add a generalized `grab` (what feels best is something like listen, and in the callback you would return either the event to let it pass (or a modified one) or None to ignore it.

**Comment by MarcAntoine-Arnaud** [comment]
Hi !

I have started to take a look to add this feature for OSX.
My personal goal is to replace the usage of Keyboard Maestro, that's why I'm focused on mapping keyboard events (an I use also osascript to run JXA and send messages to Voice Over ... ).
But actually I have some segfault when I return a different event [here](https://github.com/Narsil/rdev/blob/master/src/macos/listen.rs#L155).

I'm agreed to split with `listen` and `grab` (or `map_events`) methods.

**Comment by Narsil** [comment]
Don't know about your segfault, in my Python code I only return None or the actual event. I guess you can simply return nil and simulate your other key ?

**Comment by MarcAntoine-Arnaud** [comment]
I have tried to return something "null" but without success:
```rust
unsafe extern "C" fn raw_callback(
    _proxy: CGEventTapProxy,
    _type: CGEventType,
    cg_event: CGEvent,
    _user_info: *mut c_void,
) -> CGEvent {
    ...
    let cg_event_source = CGEventSource::new(CGEventSourceStateID::HIDSystemState).unwrap();
    CGEvent::new(cg_event_source).unwrap()
}
```

**Comment by MarcAntoine-Arnaud** [comment]
I have tried to return
```rust
*mut c_void
```
and set value to
```rust
std::ptr::null_mut()
```

And also:
```rust
Option<CGEvent>
```
and set value to
```rust
None
```

In both cases, it continue to crash ...

**Comment by Narsil** [comment]
I looked into it today and figured it out. The python Quartz library (pyobjc) actually allows you to return NULL, but the actual way to do it, is to return an CGEvent with event_type Null !.

You can check out my temporary PR (only for Mac right now).

**Comment by MarcAntoine-Arnaud** [comment]
That works perfectly on my side !
I'm using your branch right now, until you finish the unix support.
