### ISSUE TITLE
Create separate MouseMove, Wheel struct

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#21]
`EventType::MouseMove` and `EventType::Wheel` are anonymous structs. I want to write code that passes `MouseMove` `EventTypes` as arguments in a type safe way. This is not currently possible unless I provide a newtype wrapper. I suggest creating separate MouseMove and Wheel (MouseWheel seems like a better name, but that's tangential) structs that correspond to their respective EventTypes.

**Comment by maxbla** [comment]
Alternatively, make it a tuple variant. This has the disadvantage of not being self-documenting.
```rust
pub enum EventType {
   ...
   /// first coordinate is x, second is y
    MouseMove (f64, f64)
    /// first number is delta x, second is delta y
    Wheel (i64, i64)
}
```

**Comment by Narsil** [comment]
Can you provide code that fails  ? Naming the arguments of MouseMove or Wheel should not be an issue.

**Comment by maxbla** [comment]
I want to calculate how far the mouse moved between two events, so I wrote a function to do so. This is what it currently looks like
```rust
fn diff(start: &EventType, stop: &EventType) -> Option<(f64, f64)> {
    match (start, stop) {
        (EventType::MouseMove{x:x1,y:y1}, EventType::MouseMove{x:x2,y:y2}) => {
            let x = x2 - x1;
            let y = y2 - y1;
            Some((x,y))
        }
        _ => None
    }
}
```
I only ever pass it `EventType::MouseMove`, but there is no way to statically guarantee that (you can't pass anonymous structs in Rust). With a separate `MouseMove` struct, I could pass around `MouseMoves` instead, simplifying this function to
```rust
fn diff(start: &MouseMove, stop: &MouseMove) -> (f64, f64) {
    (stop.x - start.x, stop.y - start.y)
}
```
to answer your question more directly, the code that fails is
```rust
//                v Rust doesn't think this is a type
fn example(coord: {x:f64, y:f64}) -> (f64,f64) {
    (0., 0.,)
}
```
or (you'll have to imagine the context here)
```rust
match event.event_type {
//  v error: did you mean `EventType::MouseMove { /* fields */ }`?
    EventType::MouseMove => {
        ...
    }
    ...
}
```
I am forced to destructure MouseMove, even though I don't want to!

**Comment by Narsil** [comment]
Hmm why don't you store that in a struct (or tuple) of yours ?

```rust
lazy_static!{
   static ref X:f64 = 0.0;
   static ref Y:f64 = 0.0;
}
fn callback(event:Event){
    match event.event_type{
        EventType::MouseMove{x ,y} => {
            let diffX = x - *X;
            let diffY = y - *Y;
            *X = x;
            *Y = y;
        }
    }
}
```

You can IMO have all the flexibility you need that way because you probably want to time how much time has elapsed between events, you might want to keep a Vec of all recent mouse moves  and so on. I don't think there is a problem with current implementation of rdev for you to do that.

**Comment by maxbla** [comment]
> why don't you store that in a struct (or tuple) of yours ?

Good point - that makes more sense.

```rust
#[derive(Debug, Clone, Copy)]
struct MouseMoveRelative {
    x: f64,
    y: f64,
}

type MousePos = (f64, f64);

impl MouseMoveRelative {
    fn diff(start: MousePos, stop: MousePos) -> MouseMoveRelative {
        MouseMoveRelative {
            x: stop.0 - start.0,
            y: stop.1 - start.1,
        }
    }
}
```

That said, I could replace the `MousePos` type alias with `MouseMove` if `MouseMove` wasn't anonymous.

**Comment by Inc0ns1st3nt** [comment]
hmm, so that now instead of
```
enum EventType {
      ...  // other fields
      MouseMove {x, y}
}
```

```
struct Point {
     x: i32,
     y: i32
}
enum EventType {
      ...  // other fields
      MouseMove (Point)
}
```
I think this would have the benefits of allowing user to self define some more methods, such as 
```
impl Point {
    fn diff(&self, p2: Point) -> Point {
        Point {
            x: self.x - p2.x,
            y: self.y - p2.y,
        }
    }
}
```

**Comment by maxbla** [comment]
> I think this would have the benefits of allowing user to self define some more methods

It wouldn't have that benefit, as Rust doesn't allow users to impl on types from a different crate [source](https://doc.rust-lang.org/reference/items/implementations.html)

**Comment by Narsil** [comment]
I feel like having your own struct is the best course of action then no ? 

Type aliasing seems like too small a benefit compared to making sure all EventType types are close together. Another argument in that direction is that in the context of `rdev` MouseMove on its own does not mean anything. We can't (by design) listen only to MouseMove events. You can only listen to *all* events.

**Comment by Inc0ns1st3nt** [comment]
> It wouldn't have that benefit, as Rust doesn't allow users to impl on types from a different crate [source](https://doc.rust-lang.org/reference/items/implementations.html)
😓, oh wait shoot, I guess I meant, using trait:
```
trait MyCustomTrait {
    fn diff(&self, p2: Point) -> Point; 
}
impl MyCustomTrait for Point {
    fn diff(&self, p2: Point) -> Point { 
        ... // implementation detail
    }
}
```

**Comment by Inc0ns1st3nt** [comment]
> Type aliasing seems like too small a benefit compared to making sure all EventType types are close together. Another argument in that direction is that in the context of rdev MouseMove on its own does not mean anything. We can't (by design) listen only to MouseMove events. You can only listen to all events.

I am not sure if I understood your point fully.
I feel like having `Vec2` struct for both `MouseMove` and `Wheel`:
```
pub struct Vec2<T> {
    pub x: T,
    pub y: T
}
... // other code
pub enum EventType {
    KeyPress(Key),
    KeyRelease(Key),
    ButtonPress(Button),
    ButtonRelease(Button),
    MouseMove(Vec2<i32>),
    Wheel(Vec2<i8>),
}
```
In my opinion is just really different style of implementation, the difference is in using the  `EventType::MouseMove` now, you will be dealing with `struct` instead of `tuples`.
