### ISSUE TITLE
Optional Serde-based Serialization Feature

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#24]
Serialization is a handy tool for some use cases, for example it could be used to save `Event`s to a file, and replay them later. Serde is the Rust ecosystem's most popular library for data serialization. To implement serialization, all you need to do is `#[derive(Serialize, Deserialize)]` on the structs and enums in rdev.rs. The user can then choose a serialization format - JSON is popular, but serde maintains [a lengthy list](https://serde.rs/#data-formats) of supported formats. Of course this requires rdev to depend on serde, but it can be an optional feature (so disabled by default). Having an optional serde feature is fairly common, for example most of the most downloaded (according to [lib.rs](https://lib.rs/data-structures)) data-structures crates have such a dependency (I realize this is not a data structure crate).

**Comment by Narsil** [comment]
Optional Serde dependency makes sense, and does seem a bit common.

**Comment by Narsil** [comment]
Added a PR for that. I'd be happy if you could review it.
