### ISSUE TITLE
Mixing Rust types with C types

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#31]
Disclaimer: I'm not sure if this is an issue.

What is the best practice for mixing Rust types with C types? For example if there is a function `fn add_one(num: c_int) -> c_int` should we pass it an i32? I'm aware that on almost all supported platforms (and all platforms that this crate explicitly supports) `i32` is the same as `c_int`, but it is not guaranteed to be true on all platforms. I'm pretty sure that if the assumption `type c_int = i32` broke down on any platform, it would be a compile time error.

For reference, the code that piqued my interest is
```rust
static TRUE: i32 = 1;
static FALSE: i32 = 0;
...

xtest::XTestFakeKeyEvent(display, code, TRUE, 0);
```
where `XTestFakeKeyEvent` takes a `c_int` parameter. It seems like a simple change in this case to make `TRUE` and `FALSE` `c_ints`, but if we decide to switch to `c_*` types everywhere, keycodes.rs will need much more substantial changes.

Also as with all issues I submit in this repo, I'd be happy to make a PR fixing this.

**Comment by Narsil** [comment]
I think c_int might be better. I hacked a bunch of this pretty fast at start.

As long as no such type is leaked outside the library we're fine I guess.

I also noted some inconsistencies, either within library, and/or rust bindings I'm using. For instance in X11, IIRC the keycodes you receive through XRecord is smaller that the keycode you need to send to simulate a keystroke, so things like this.

**Comment by maxbla** [comment]
> I think c_int might be better. I hacked a bunch of this pretty fast at start

Cool. I'm working on a PR.

> I also noted some inconsistencies, either within library, and/or rust bindings I'm using

Yeah, I noticed that too when trying fix this issue. It seems like you generally used the widest type (i.e. if Mac used `u16` and Linux used `u32`, you picked `u32` for the rdev public api). This is generally a great idea, but I think we should look carefully at similar decisions, as linux/X11 never seems to actually use keycodes outside the `u16` range...

**Comment by Narsil** [comment]
keycodes no, but they do use keysym that are in u32 range, and function seem to receive arbitrary thing between keycode and keysym (x11 is *really* ugly...). Also note that linux is not perfect support because I did not implement the dead keys keyboards (you need to read the correct config file that will enable you to decide for eacute+e = é for instance, it's pretty messy..)

**Comment by maxbla** [comment]
I wasn't thinking about dead keys - my keyboard doesn't even use them! In that case it makes the most sense that the public Key api uses `u32`.

I said we should look carefully at similar decisions though, and I stand by that. For example, MouseMove uses `f64`? On Linux, it is a 16-bit integer, on mac it is a CGFLoat, which is `f32` on 32 bit processors and `f64` bit on 64 bit processors. On windows it is a DWORD i.e. `i32`. Now I'm not sure why mac uses a float and everyone else uses integers. Does macOS consider sub-pixel placement of the cursor? idk, but I think I would prefer if the public api used an i32 instead, and on mac the f64 was rounded and/or truncated to an i32. After all, has anyone ever moved a mouse more than 2,147,483,647 pixels?

**Comment by Narsil** [comment]
I can't speak for MacOS guys. They do seem to make use of the floating factor for the Wheel (trackpad mouvement). 

It could be that there are using the same alignement for Mouse move.
