### ISSUE TITLE
[Bug] Maximum number of client reached with opening display too often

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [Narsil/rdev#36]
With the current implementation of opening a new `*mut xlib::Display` via `xlib::XOpenDisplay(ptr::null())` will result in the program to panic, once `simulate` has been called to often.
Panic message:
>  Maximum number of client reached 

It seems that the maximum client is `256` by default, ref [stackexchange link](https://unix.stackexchange.com/questions/498652/does-x-window-have-a-maximum-number-limit-on-clients).

A better way to approach this, might be having a `Struct` named `Rdev` for example, which will hold the reference to 3 x11 display object, one for `simulate`, two for `listen`.

```
struct Rdev {
    display: *mut xlib:Display,
    ...
}
```

**Comment by Inc0ns1st3nt** [comment]
A bit of a follow up with this issue, the new implementation using struct, will also require us to use a different way to add uniform documentation to our methods:
 ```
pub trait Simulator {
    /// Sending some events
    ///
    /// ```no_run
    /// use rdev::{simulate, Button, EventType, Key, SimulateError};
    /// use std::{thread, time};
    ///
    /// fn send(event_type: &EventType) {
    ///     let delay = time::Duration::from_millis(20);
    ///     match simulate(event_type) {
    ///         Ok(()) => (),
    ///         Err(SimulateError) => {
    ///             println!("We could not send {:?}", event_type);
    ///         }
    ///     }
    ///     // Let ths OS catchup (at least MacOS)
    ///     thread::sleep(delay);
    /// }
    ///
    /// fn my_shortcut() {
    ///     send(&EventType::KeyPress(Key::KeyS));
    ///     send(&EventType::KeyRelease(Key::KeyS));
    ///
    ///     send(&EventType::MouseMove { x: 0.0, y: 0.0 });
    ///     send(&EventType::MouseMove { x: 400.0, y: 400.0 });
    ///     send(&EventType::ButtonPress(Button::Left));
    ///     send(&EventType::ButtonRelease(Button::Right));
    ///     send(&EventType::Wheel {
    ///         delta_x: 0,
    ///         delta_y: 1,
    ///     });
    /// }
    /// ```
    fn simulate(&self, event_type: EventType)-> Result<(), SimulateError>;
} ```

**Comment by maxbla** [comment]
Could you give a minimal working example that causes the `Maximum number of client reached` panic, for testing's sake?

A struct storing some fixed number of `xlib::Display` pointers could be a good fix, but it would be a substantial api change. Furthermore, it wouldn't be a perfect fix, as users could still instantiate multiple such structs, and exceed the limit that way. On the other hand, once a struct is initalized, it is guraanteed to not cause a `Maximum number of client reached` error. I think querying the X server for how many more displays it can support before opening a display has the potential to be a better fix. From a cursory glance, it might be possible to do this with the `X-Resource` extension.

**Comment by Narsil** [comment]
There is a much simpler fix, which does no need to hold a display pointer, which is to close the display after simulating.

**Comment by Inc0ns1st3nt** [comment]
> There is a much simpler fix, which does no need to hold a display pointer, which is to close the display after simulating.

I am using your crate to write an auto clicker, sometimes, the user might have something like 
mouse click 50 times with 5ms delay in between, it might be too costly to open and close a Display pointer 50 times with 5ms delay.

**Comment by Inc0ns1st3nt** [comment]
> Could you give a minimal working example that causes the `Maximum number of client reached` panic, for testing's sake?

```
let delay = time::Duration::from_millis(10); // 10 milli secs, change to 5 would 

for _i in 0..300 {
    simulate(EventType::ButtonPress(Button));
    simulate(EventType::ButtonRelease(Button)); // I think this line can be removed 
    thread::sleep(delay);  
}
```

> A struct storing some fixed number of `xlib::Display` pointers could be a good fix, but it would be a substantial api change. Furthermore, it wouldn't be a perfect fix, as users could still instantiate multiple such structs, and exceed the limit that way.

I see, what you mean, but that means the user will need to create about ~250 instances of the `struct`, which doesn't make sense. They would just create one to simulate keyboard/mouse events. Right??

**Comment by Narsil** [comment]
> I am using your crate to write an auto clicker, sometimes, the user might have something like
mouse click 50 times with 5ms delay in between, it might be too costly to open and close a Display pointer 50 times with 5ms delay.

It might, can you check ? I'm not sure it will, opening a display socket should be pretty fast.
On the other hand of your usage, are people that use to simulate shortcuts sometimes only, and there, it's preferable to not keep around anything open. As @maxbla said, using a struct would need a modification in the API, which will need serious thinking to do that properly. 

> I see, what you mean, but that means the user will need to create about ~250 instances of the struct, which doesn't make sense. They would just create one to simulate keyboard/mouse events. Right??

Simulate takes references so no you don't have to create n structs.

```rust
let delay = time::Duration::from_millis(10); // 10 milli secs, change to 5 would 
let press = EventType::ButtonPress(Button);
let release = EventType::ButtonRelease(Button);
for _i in 0..300 {
    simulate(&press);
    simulate(&delay); // this is definitely needed, but some OSes will compensate if you don't put them, not all of them though, and some apps WILL fail.
    thread::sleep(delay);  
}
```

**Comment by maxbla** [comment]
> Simulate takes references so no you don't have to create n structs.

I was just pointing out that a consumer of the hypothetical struct-based API could still shoot themselves in the foot, not that it would make sense. (The way to fix it in theory is to make the struct's new method return an Option<Self>).

> It might, can you check ?

Can we add a test for this (I'd be happy to do so) and then we can be sure it will never be an issue again.

**Comment by Narsil** [comment]
Doing massive clicks on a test that is run by CI/knowing user is fine, but clicking everywhere for someone running `cargo test` naïvely is probably bad behavior, no ? We *are* hitting the real OS after all.

**Comment by maxbla** [comment]
We could put the test behind an optional feature flag (that CI sets), but I'm honestly not a fan of this idea because it makes it harder for me (and newcomers) to test the code (`cargo test --all-features` vs `cargo test`). We can try to minimize the impact of testing by (for example) sending 50 shift key up/down events (maybe not shift, as 5 shift presses in windows -> sticky-keys). Worst case, that causes the user to accidentally type a letter in the wrong case. I suppose an even worse case is improperly triggering a key combination, but we could have a timeout of 10ms to send a bunch of events, so the user really probably won't notice.

In a similar vein to the shift example, we could mouse wheel up and down equal amounts repeatedly.

**Comment by maxbla** [comment]
Upon further inspection, it seems we can send only keyup events, which appear do nothing if the key isn't already pressed. This testing method is highly non-intrusive for users who type `cargo test` without considering the possibilities.
