### ISSUE TITLE
use single-threaded tests

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#40]
If multiple tests simulate inputs and multiple tests listen, they will interfere with each other. We need to test with `cargo test -- --test-threads=1`

**Comment by Narsil** [comment]
What about using a macro to do serial tests ?

Something like https://docs.rs/serial_test/0.4.0/serial_test/ ? 

`cargo test` should work no matter what right ?

**Comment by maxbla** [comment]
> cargo test should work no matter what right ?

Ideally `cargo test` would work without the `--test-threads=1` flag, to make testing easy for new contributors and to eliminate false test failures for you and me. That said, I like to avoid pulling in new dependencies where possible. I wonder if there are any better options for local development obviously it's easy to include the flag for CI (I did in my PR). Maybe some way to make the error message on test failure include "Did you make sure to run with --test-threads=1?".

**Comment by Narsil** [comment]
Hmm serial test is a very simple macro:

```rust
    lazy_static! {                                                             
        /// A global lock since most tests need to run in serial.              
        static ref SERIAL_TEST_MUTEX: Mutex<()> = Mutex::new(());              
    }                                                                          
                                                                               
    /// Macro to crate a serial test, that locks the `SERIAL_TEST_MUTEX` while 
    /// testing.                                                               
    macro_rules! serial_test {                                                 
        (fn $name: ident() $body: block) => {                                  
            #[test]                                                            
            fn $name() {                                                       
                let guard = SERIAL_TEST_MUTEX.lock().unwrap();                 
                // Catch any panics to not poisen the lock.                    
                if let Err(err) = panic::catch_unwind(|| $body) {              
                    drop(guard);                                               
                                                                               
                    panic::resume_unwind(err);                                 
                }                                                              
            }                                                                  
        };                                                                     
    }                                        

    serial_test!{
       fn mytest(){
       } 
    }
```
(I took that from somewhere on the internet for another pet project, and it works pretty well).

Ideally we would not need that, but considering that we are hitting the live OS, and that x11 for instance is *not* thread-safe, I don't see how we can avoid it.

**Comment by Narsil** [comment]
Btw 

> I like to avoid pulling in new dependencies where possible.

Me too.

**Comment by maxbla** [comment]
> very simple macro

yes, except that it uses `parking_lot`'s `ReentrantMutex`, which requires building all of parking_lot and all of `parking_lot`'s dependencies. That said, since this is a dev-dependency, it's not a big deal.

> x11 for instance is not thread-safe

Correct me if I'm wrong, but Xlib is not thread safe. Xserver implementations seen in the wild are frequently concurrent and parallel.

**Comment by Narsil** [comment]
> 
> yes, except that it uses `parking_lot`'s `ReentrantMutex`, which requires building all of parking_lot and all of `parking_lot`'s dependencies. That said, since this is a dev-dependency, it's not a big deal.
> 

The code I included does not require parking-lot, it's not as clean as `#[serial]` but it would do the job without additional dependency.

> > x11 for instance is not thread-safe
> 
> Correct me if I'm wrong, but Xlib is not thread safe. Xserver implementations seen in the wild are frequently concurrent and parallel.

You are probably right, I'm definitely not an expert it that area.
I read on a lot of bits of codes trying to figure out how to implement grabbing mechanism close to the MacOS and windows ones, and lots of them said to be very careful when using threads because x11 was not thread safe (x11, xlib, I'm not talking about a particular implementation here). That's about the extent of my knowledge there.

**Comment by maxbla** [comment]
> The code I included does not require parking-lot, it's not as clean as #[serial] but it would do the job without additional dependency.

I misunderstand, I thought you were saying that's exactly how serial_test works. I would prefer a (dev-)dependency with a laser focus like serial_test to a hand-written macro that does the same thing. The intent is more clear, and serial_test will stay up to date with changes to the rust language.

> You are probably right, I'm definitely not an expert it that area.

Well I'm certainly not either - this is my first foray into the weeds of X11, but the reason I mention this distinction is not to be pedantic, but because xlib has an alternative - XCB (X C BIndings). I just read [an article](https://www.x.org/wiki/guide/xlib-and-xcb/) or [two](https://www.remlab.net/op/xlib.shtml) comparing them. Supposedly, XCB handles threading rather well in comparison to Xlib, and was designed in response to the shortcomings of Xlib.
