### ISSUE TITLE
Emit special keys

### ISSUE THREAD

**Issue by flukejones** [Narsil/rdev#49]
I was looking around for a crate which can emit specials like "Sleep", is it possible to do so with this?

**Comment by Narsil** [comment]
What do you mean specials like sleep ? There is a Sleep key on your keyboard ?

I don't think they exist on standard keyboards. When sending keys that are beyond standard keys, you can detect if they get triggerred with the `listen` example. If they get detected, you will most likely receive `KeyPress::Key::Unknow(somenumber)`. Then you can resend send as you want.

However, I didn't check how various OSes handle extended keyboards, they probably use different mechanisms, and it could be a mechanism not handled by this lib.

**Comment by flukejones** [comment]
Hmm, thanks for the tips. Yeah I've written a small app to grab the keypresses from a keyboard which the Linux kernel doesn't register a group of keys on (which are activated with fn). I was hoping to find a crate that could emit certain key types, but I'm guessing this might need to actually be done in the kernel driver.

This crate will still be useful for emitting something like macros for me though :)

**Comment by flukejones** [comment]
I guess what I mean is something like what evdev shows here:

```
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 129 (KEY_AGAIN)
    Event code 130 (KEY_PROPS)
    Event code 131 (KEY_UNDO)
    Event code 132 (KEY_FRONT)
    Event code 133 (KEY_COPY)
    Event code 134 (KEY_OPEN)
    Event code 135 (KEY_PASTE)
    Event code 136 (KEY_FIND)
    Event code 137 (KEY_CUT)
    Event code 138 (KEY_HELP)
    Event code 161 (KEY_EJECTCD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
```

What I'm trying to do is emit keys like those

**Comment by Narsil** [comment]
Try running `cargo run --example listen` and press those keys if they show Up. I don't have such a keyboard so I can't really test (END, DOWN, PAGEDOWN and DELETE are taken care of by this crate)

**Comment by flukejones** [comment]
Turns out I needed to emulate a device using uhid.
