### ISSUE TITLE
What are Key::IntlBackslash and Key::kpDelete?

### ISSUE THREAD

**Issue by maxbla** [Narsil/rdev#51]
In particular, how is `Key::IntlBackslash` different from `Key::BackSlash`? I couldn't find any info about IntlBackslash when searching the web.

Why is `kpDelete` specified separately from normal delete, when all the other num pad keys (pageup/down, home, end, insert, arrow keys) are not?

These are the only two keys I'm having trouble with in #47.

**Comment by Narsil** [comment]
IntlBackslash *is* a different keycode from BackSlash (see Linux and windows), however it might be a key not present on standard azerty layout (can't say I can press it either).

The codes were taken from X11 and Windows enums, so those backend can definitely send them our way (in listen/grab).

KpDelete, is also a different key from Delete. However it seem that modern OSes, prefer to mimick sending the alternatives keycodes instead I'm guessing (can't test right now). Again, the keycodes still exist in the various systems, so they might get sent our way.

What is the problem exactly ?

**Comment by maxbla** [comment]
In #47 I'm very close to being able to map every rdev key to an [evdev-rs](https://github.com/ndesh26/evdev-rs) [key](https://docs.rs/evdev-rs/0.4.0/evdev_rs/enums/enum.EV_KEY.html) (essentially a key defined in [linux/input-event-codes.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)). The two that I can't find a mapping for are IntlBackslash and kpDelete. There is a kpSlash key in the linux header, and there are a few delete-like keys (KEY_DELETEFILE, KEY_DEL_EOL, etc.) but I'm not sure if those are correct.

**Comment by Narsil** [comment]
Hmm it's not evident enough on how to handle those different mapping, just override those to backslash and delete and we're good I think (with a comment at least)

**Comment by maxbla** [comment]
Alright, seems good enough for now, and this issue can be closed. ~Can you provide me an internet reference of some sort for IntlBackslash? I can only find [this](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values), which doesn't really explain what it is, only indicates that it is Windows-only.~ I found [a helpful picture](https://github.com/emscripten-core/emscripten/pull/5492#issuecomment-326046667).

**Comment by Narsil** [comment]
Ahaha yes, pretty obscure keys...
