### ISSUE TITLE
[Feature Request] Hardware Id

### ISSUE THREAD

**Issue by rufreakde** [Narsil/rdev#56]
Would it be possible to add the hardware Id to the EventType?

I have a usecase to use several different keyboards and mice and would love to distiguish them via this unique hardware id.

```
/// In order to manage different OS, the current EventType choices is a mix&match
/// to account for all possible events.
#[derive(Debug)]
pub enum EventType {
    /// The keys correspond to a standard qwerty layout, they don't correspond
    /// To the actual letter a user would use, that requires some layout logic to be added.
    KeyPress(Key),
    KeyRelease(Key),
    /// Some mouse will have more than 3 buttons, these are not defined, and different OS will
    /// give different Unknown code.
    ButtonPress(Button),
    ButtonRelease(Button),
    /// Values in pixels
    MouseMove {
        x: f64,
        y: f64,
    },
    /// Note: On Linux, there is no actual delta the actual values are ignored for delta_x
    /// and we only look at the sign of delta_y to simulate wheelup or wheeldown.
    Wheel {
        delta_x: i64,
        delta_y: i64,
    },
}
```

**Comment by Narsil** [comment]
Sorry I have no plans on adding that just yet as it would significantly impact the API, I don't even know how those are handled in each OS.

If you manage to get something done, I would definitely love to review a PR and incorporate that if you manage to find a solution that does not change that much the API. However I think this information should lie `Event` Struct, not `EventType`.

You should definitely check out the source code to see the OS-specific function I use to get started.

**Comment by rufreakde** [comment]
Thank you for the feedback I will look into the sourcecode and fork the project to play around with it. ;)
