### ISSUE TITLE
[Feature Request] Add Display trait to Key enum

### ISSUE THREAD

**Issue by alextremblay** [Narsil/rdev#66]
Hello,

I would like to add the display trait to the Key enum. The way i picture this working is that all keys would display the same as they do in Debug, except the `Key*` variants would print without the `Key` prefix, the `Num*` variants would print without the `Num` prefix, and the punctuation characters (`- = [ ] \ ; ' , . / `) would print literal punctuation characters. The keypad variants would remain the same, to distinguish them from from the regular number variants.

Ex:
```rust
use rdev::Key::*;
fn main() {
    println!("{} / {} / {} / {} / {} / {} / {}", Alt, F1, Num1, Minus, KeyQ, LeftBracket, Kp6)
}

```
would print:
`Alt / F1 / 1 / - / Q / [ / Kp6`

I can implement this and submit a PR if you'd like

**Comment by Narsil** [comment]
No I'm sorry but we cannot have this tbh. 

Key refers to a real Keyboard KEY (as in a physical stuff that you press). It is NOT linked (directly at least) to what is printed on screen.

So KeyA might be a `A` or a `Q` or any other letter. Changing the display will only increase the confusion.

If you want to know what is being written, you **need** to pass it to the Keyboard state machine that will know what to do with those characters and the eventual strings/chars that get emitted. There's no shortcut around it.

ofc if you know your device and want to do something like that, feel free to implement something on top, but it does not belong in this lib IMO.

**Comment by alextremblay** [comment]
Ahhhh, right... because different keyboard layouts produce different characters for the same keycode...

ok, no problem. I'll close the PR then. Thanks!
