### ISSUE TITLE
unstable_grab isn't blocking

### ISSUE THREAD

**Issue by saml-dev** [Narsil/rdev#69]
I'm trying out the code block in the README for `unstable_grab` but the part that says it should be blocking isn't blocking. I've gotten the regular listener example to work, but the grab just immediately exits the program. My goal is to allow simulating global key rebinds by blocking events (returning None) and then sending a different key. For example, turning a press of caps lock into escape. I'm on Mac OS on an M1 chip. Thank you for any help.

**Comment by alextremblay** [comment]
Can you give us a code example?

**Comment by SamLewis0602** [comment]
Sure, I've copied everything directly from the README so far. This is the sample that is working, using the `listen` API:
```rust
use rdev::{listen, Event};

// This will block.
if let Err(error) = listen(callback) {
    println!("Error: {:?}", error)
}

fn callback(event: Event) {
    println!("My callback {:?}", event);
    match event.name {
        Some(string) => println!("User wrote {:?}", string),
        None => (),
    }
}
```

This is the sample that is NOT working, using the `unstable_grab` API:
```rust
#[cfg(feature = "unstable_grab")]
use rdev::{grab, Event, EventType, Key};

#[cfg(feature = "unstable_grab")]
let callback = |event: Event| -> Option<Event> {
    if let EventType::KeyPress(Key::CapsLock) = event.event_type {
        println!("Consuming and cancelling CapsLock");
        None  // CapsLock is now effectively disabled
    }
    else { Some(event) }
};
// This will block.
#[cfg(feature = "unstable_grab")]
if let Err(error) = grab(callback) {
    println!("Error: {:?}", error)
}
```

The issue is that the call to `grab` doesn't block as the comment states it should. So the program just exist immediately. Let me know if I can provide any other details.

**Comment by SamLewis0602** [comment]
```
#[cfg(feature = "unstable_grab")]
use rdev::{grab, Event, EventType, Key};

fn main() {
  #[cfg(feature = "unstable_grab")]
  let callback = |event: Event| -> Option<Event> {
    if let EventType::KeyPress(Key::CapsLock) = event.event_type {
      println!("Consuming and cancelling CapsLock");
      None // CapsLock is now effectively disabled
    } else {
      Some(event)
    }
  };
  // This will block.
  #[cfg(feature = "unstable_grab")]
  if let Err(error) = grab(callback) {
    println!("Error: {:?}", error)
  }
}
```

**Comment by SamLewis0602** [comment]
Let me know if you have any thoughts, hoping to get the `unstable_grab` feature working. Hit me up if you could use more details!

**Comment by SamLewis0602** [comment]
I realized I should share my actual goal. I'm hoping to intercept keyboard events and remap them to different keys. For example, mapping caps lock to escape. Based on your README, it seemed like the `unstable_grab` api was the only way to actually stop an event from propagating. If I can use the `listen` api and I missed it, please let me know! 😁

**Comment by Narsil** [comment]
Very slow to the party, but no listen is not intended to do that.

Various OSes have different way to handle this use case.

`grab`  is the only way to go to do that. 

This crate was written before M1 and the new MacOS, maybe they changed something in the grab API (it was always very tricky to write something consistent across OS for grabbing)

What exactly happens when grabbing on MacOS ?

**Comment by IronLad85** [comment]
@Narsil Any update on the grab issue in macOS?

**Comment by saml-dev** [comment]
Hey @Narsil , no worries haha I've been there. `grab` was doing nothing when I tried it, the call wouldn't block at all. So the script would just end with no output

**Comment by gmatht** [comment]
Also doesn't block on WSL (Windows 11) and Xephyr.

**Comment by Narsil** [comment]
WSL is going to be almost impossible, it's afaik an emulation layer meaning accessing the OS internals is super hard.

I should receive a Mac in the coming weeks, I can maybe look a little bit more into it.
In the meantime PRs are welcome :) (I'll merge if there's at least 1 other user claiming it works)

**Comment by saml-dev** [comment]
Funny enough, I came back to this a few weeks ago and found the grab API was working on my M1 macbook air. No clue what changed (if anything), could be Mac OS updates too. Who knows 😂 I'll close this issue since I no longer see it.

**Comment by gmatht** [comment]
> 

Why would it be harder to get the internals of a WSL2 VM? (Obviously grabbing the internals of the VM wouldn't grab the internals of the host kernel, but not sure why that would be needed for Xephyr)
