### ISSUE TITLE
No option to listen for KeyUp or KeyDown

### ISSUE THREAD

**Issue by KunalBagaria** [Narsil/rdev#71]
I have a code that uses the KeyPress enum and needs to register a key press only once, but continuous press of that key registers it multiple times

**Comment by kb24x7** [comment]
Was hoping there could be an option for KeyUp and KeyDown

**Comment by michaelritsema** [comment]
EventType::KeyRelease and EventType::KeyPress

**Comment by Narsil** [comment]
@KunalBagaria the OS level will decide if there's a single KeyPress or many, this is NOT decided at the application level.
What this crate reports is what the OS sends.
For historical reasons, OSes might report sticking a keypress as many keypresses.

You might have seen remanent keypress on Windows, other OSes have similar options. You can do some manipulation within your app to change that behavior, but this is beyond this crate purpose and design.

**Comment by eboody** [comment]
The way I handle this is by passing a state struct.

[Here](https://github.com/eboody/caps/blob/main/src/main.rs)'s an example of how I'm doing it
