### ISSUE TITLE
rdev fails to compile

### ISSUE THREAD

**Issue by ZackGabri** [Narsil/rdev#8]
trying to compile redev 0.3 fails to compile with the following error
![](https://zackgabri.is-inside.me/NqMA4w9I.png)

i'm using the latest version of stable rust (1.42.0)

**Comment by Narsil** [comment]
I uploaded version 0.3.1 which includes winapi feature processthreadsapi, which should solve your bug.

It seems quite worrying that running examples and tests does not seem to detect that on windows....
