### ISSUE TITLE
Any plans for wayland support?

### ISSUE THREAD

**Issue by rithulkamesh** [Narsil/rdev#82]
Since some major linux distros are using Wayland now (Ubuntu 22.04), are there any plans to get wayland support along with the x11 in rdev?

**Comment by DomiRusz24** [comment]
As far as I am aware, every WayLand application is "sandboxed" and can only receive key strokes and clicks if the user is focused on it. You can't read inputs globally like in x11. Same with display, every application can see itself only. It's safer, (preventing most simple keyloggers) more efficient, but as a drawback you can't do stuff like this.

**Comment by Narsil** [comment]
Hi, that would be nice to have support. 

I think @DomiRusz24 is correct, wayland was exactly built to prevent global listeners like this (which ARE a security threat).
However, maybe there's a way like in macOS to give higher privileges where applicable.
