### ISSUE TITLE
Unclear on how to process combinations of keys.

### ISSUE THREAD

**Issue by alphastrata** [Narsil/rdev#89]
Problem: 

I'd like to process a group of keys i.e `ctrl+shift+p` to do my thing -- I cannot really see from the examples/docs how one would go about this, without grouping a bunch of the `Event`'s and just checking to see the `time` field they share is close enough in proximity to one another... which, seems hard.

Is there a better way?

**Comment by Narsil** [comment]
There's no timing, just check for pressed/released. If it's not released it's pressed.

**Comment by alphastrata** [comment]
awesome :) TY
