### ISSUE TITLE
Add Super/Command/Win key support

### ISSUE THREAD

**Issue by fayez-nazzal** [Narsil/rdev#90]
Hello, Thank you for creating this crate.

I've checked the `keycodes.rs` file, searching for the OS-specific key, which is the 'Command' key in macOS or the 'Super'/'Win' key in Linux and windows, and I can't find any. 

Could you support this key so that users can automate OS-specific commands?

**Comment by Narsil** [comment]
It's called meta which is a more generic name that fits better all oses I think.

**Comment by fayez-nazzal** [comment]
> It's called meta which is a more generic name that fits better all oses I think.

Alright then, I got it.

I am closing this issue. Thanks for this great library again.
