### ISSUE TITLE
MacOS "HOME" causes sticky "Fn"

### ISSUE THREAD

**Issue by fufesou** [Narsil/rdev#93]
After simulating keys here
![image](https://user-images.githubusercontent.com/13586388/209773518-60492037-f1ef-4cdd-92fc-9391c1ca35a3.png)

The "Fn" seems keeping pressed.
"E" results "Fn" + "E",
"D" results "Fn" + "D",
"H" results "Fn" + "H"

https://user-images.githubusercontent.com/13586388/209773872-5a674950-27b2-49c1-b4ac-c4f11d4b8a9b.mp4

## How to reproduce
```rust
use rdev::{simulate, EventType, Key, SimulateError};
use std::{thread, time};

fn send(event_type: &EventType) {
    let delay = time::Duration::from_millis(20);
    match simulate(event_type) {
        Ok(()) => (),
        Err(SimulateError) => {
            println!("We could not send {:?}", event_type);
        }
    }
    // Let ths OS catchup (at least MacOS)
    thread::sleep(delay);
}

fn main() {
    // Press Home
    send(&EventType::KeyPress(Key::Unknown(0x73)));
    // Release Home
    send(&EventType::KeyRelease(Key::Unknown(0x73)));

    // Press h
    send(&EventType::KeyPress(Key::Unknown(0x04)));
    // Release h 
    send(&EventType::KeyRelease(Key::Unknown(0x04)));

    thread::sleep(std::time::Duration::from_millis(1_000));

    // Press h
    send(&EventType::KeyPress(Key::Unknown(0x04)));
    // Release h
    send(&EventType::KeyRelease(Key::Unknown(0x04)));
}
```

**Comment by Narsil** [comment]
You're using `Unknown` keys so behavior is not guaranteed by any means.

You should check out the MacOS docs but I can't really help here. 

`KeyPress(Key::H)` should work no ? (Without the unknown before)

**Comment by fufesou** [comment]
I saw `unknown` keys just pass the codes down to `CGEventRef`.
This issue may be caused by the [global event state table](https://developer.apple.com/documentation/coregraphics/cgeventsourcestateid#:~:text=global%20event%20state%20table) in `MacOS`. 
I also ask a question [here](https://stackoverflow.com/questions/74938870/sticky-fn-after-home-is-simulated-programmatically-macos).

Close as it is not `rdev`'s issue.
