### ISSUE TITLE
Send keyboard events to a specific process/PID ?

### ISSUE THREAD

**Issue by ykong1337** [Narsil/rdev#96]
I want to do some background operations.
Send keyboard events to a specific process/PID ?

**Comment by Narsil** [comment]
Everything in this lib is *global*.

So no it's not possible to send kb events to specific processes. I'm not even sure this is possible

**Comment by michaelritsema** [comment]
I use this (r dev) to listen but send events on macOS with a few of my own projects. https://github.com/michaelritsema?tab=repositoriesLook for ezmacos and ioshd repos for examples. I’ve also done this on windows with built in .net api Sent from my iPhoneOn Jan 27, 2023, at 9:40 AM, Nicolas Patry ***@***.***> wrote:﻿
Closed #96 as completed.
